package com.mihua.yangben.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "ZOO".
 */
public class ZooDao extends AbstractDao<Zoo, Long> {

    public static final String TABLENAME = "ZOO";

    /**
     * Properties of entity Zoo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Bean = new Property(1, String.class, "bean", false, "BEAN");
    }

    private final Zoo.CatConverter beanConverter = new Zoo.CatConverter();

    public ZooDao(DaoConfig config) {
        super(config);
    }

    public ZooDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"ZOO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"BEAN\" TEXT);"); // 1: bean
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ZOO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Zoo entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        FourFuranBean bean = entity.getBean();
        if (bean != null) {
            stmt.bindString(2, beanConverter.convertToDatabaseValue(bean));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Zoo entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        FourFuranBean bean = entity.getBean();
        if (bean != null) {
            stmt.bindString(2, beanConverter.convertToDatabaseValue(bean));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public Zoo readEntity(Cursor cursor, int offset) {
        Zoo entity = new Zoo( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.isNull(offset + 1) ? null : beanConverter.convertToEntityProperty(cursor.getString(offset + 1)) // bean
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, Zoo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBean(cursor.isNull(offset + 1) ? null : beanConverter.convertToEntityProperty(cursor.getString(offset + 1)));
    }

    @Override
    protected final Long updateKeyAfterInsert(Zoo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    @Override
    public Long getKey(Zoo entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Zoo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }

}
